# Generated by Django 3.2.4 on 2021-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_analytics_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.CharField(max_length=120)),
                ('reasons', models.JSONField()),
            ],
        ),
    ]
